name: FFmpeg GPU Processing

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    paths:
      - 'input_videos/**'  # Runs only when files in this folder are updated

jobs:
  ffmpeg:
    runs-on: ubuntu-latest  # Change to a GPU-enabled runner if available
    container: nvidia/cuda:11.8.0-runtime-ubuntu22.04  # GPU-enabled FFmpeg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y wget unzip ffmpeg libfdk-aac2

      - name: Download MP4 file
        run: |
          wget -O Migration2023_1080p.mp4 "http://ts.karaj.online:8080/Migration2023_1080p.mp4"

      - name: Process video with FFmpeg (GPU Acceleration)
        run: |
          mkdir -p output_videos
          input_file="Migration2023_1080p.mp4"
          output_file="output_videos/$(basename "$input_file" .mp4)_processed.mp4"
          /usr/bin/ffmpeg -hwaccel cuda -i "$input_file" -map_chapters -1 -threads 4 -map 0 \
            -codec:v h264_nvenc -preset fast -b:v 5M \
            -codec:a aac -b:a 192k -codec:s mov_text -copyts -y "$output_file"
            
      - name: Upload processed video
        uses: actions/upload-artifact@v4
        with:
          name: processed_videos
          path: output_videos/
          retention-days: 7  # Adjust retention period
